### PR TITLE
feat(PHXCMS-183): Replace TextControl with core/paragraph for branding-box

### PR DESCRIPTION
**Pull request by elsurn**
This PR removes TextControl and adds core/paragraph as innerBlocks to Branding Box. 

[Prefilled Branding Boxes](https://contestcol.atlassian.net/browse/PHXCMS-183)

### CODE REVIEW

**Review by doublethug — APPROVED** [review]
Looks good to me

**Comment by col-tom** [comment]
Thanks - Fine for me as well, but do you know why the image selection (localhost/standalone) doesen't work anymore?

Bildschirmfoto 2021-03-24 um 08 30 10

**Comment by elsurn** [comment]
> Thanks - Fine for me as well, but do you know why the image selection (localhost/standalone) doesen't work anymore?
> 
> Bildschirmfoto 2021-03-24 um 08 30 10

@col-tom I didn't know it was working before for localhost I was always using 'insert from url' to test. Maybe @doublethug can help here? 🤔

**Comment by col-tom** [comment]
> > Thanks - Fine for me as well, but do you know why the image selection (localhost/standalone) doesen't work anymore?
> > Bildschirmfoto 2021-03-24 um 08 30 10
> 
> @col-tom I didn't know it was working before for localhost I was always using 'insert from url' to test. Maybe @doublethug can help here? 🤔

hmm, it worked months ago - don't let's waste too much time here

**Pull request merged**
